
server:
  port: 8188
spring:
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: classpath:/templates/
    settings.template_update_delay: 0
  data:
     mongodb:
      uri: mongodb://192.168.1.42:27017/test
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boos
    username: lu
    password: 199462


