

#    spring.datasource.url=jdbc:mysql://localhost:3306/test
#    spring.datasource.username=root
#    spring.datasource.password=
#    spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#    spring.datasource.druid.initial-size=1
#    spring.datasource.druid.min-idle=1
#    spring.datasource.druid.max-active=20
#    spring.datasource.druid.test-on-borrow=true
#    spring.datasource.druid.stat-view-servlet.allow=true
#spring:
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/taotao
#    username: lu
#    password: 123456
druid:
    url: jdbc:mysql://localhost:3306/jd_order?useUnicode\=true&characterEncoding\=UTF8mb4
    username: root
    password: 199462
    initial-size: 1
    min-idle: 1
    max-active: 20
    test-on-borrow: true
mybatis:
    type-aliases-package: springboot.ltq.entity
    mapper-locations: classpath:mapper/*.xml

server:
  port: 8188
spring:
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: classpath:/templates/
    settings.template_update_delay: 0



